# Generated by Django 3.2.9 on 2021-11-19 09:04

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('interest', models.CharField(choices=[('Accounts', 'Accounts'), ('Administration', 'Administration'), ('Human Resources', 'Human Resources'), ('Technical', 'Technical'), ('Sales', 'Sales')], default=None, max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('cover_letter', models.TextField()),
            ],
            options={
                'verbose_name': 'Career query',
                'verbose_name_plural': 'Career queries',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Dealer Query',
                'verbose_name_plural': 'Dealers enquiries',
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Fleet Query',
                'verbose_name_plural': 'Fleet enquiries',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, choices=[('USA', 'United States of America')], default=None, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=11)),
                ('postcode', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('order_notes', models.TextField(blank=True)),
                ('about_us', models.CharField(blank=True, choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('linkedIn', 'linkedIn'), ('YouTube', 'YouTube'), ('Friend', 'Friend'), ('News Article', 'News Article'), ('Saw one on the street', 'Saw one on the street'), ('Self Research/Browsing', 'Self Research/Browsing'), ('Conference', 'Conference')], default=None, max_length=255)),
                ('t_c', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=home.models.upload_review_photo)),
            ],
            options={
                'verbose_name': 'Photos',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
