# Generated by Django 3.2.8 on 2021-11-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211103_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vid',
            new_name='video',
        ),
    ]
