# Generated by Django 3.2.8 on 2021-11-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211111_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerrequest',
            options={'verbose_name': 'Career query', 'verbose_name_plural': 'Career queries'},
        ),
    ]
