# Generated by Django 3.2.9 on 2021-11-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211119_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, choices=[('Customer Enquiry', 'Customer Enquiry'), ('Vendor Enquiry', 'Vendor Enquiry'), ('Press Coverage', 'Press Coverage'), ('Investors', 'Investors'), ('Others', 'Others')], default=None, max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
    ]
