# Generated by Django 3.2.9 on 2021-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_link', models.CharField(max_length=255)),
                ('black_link', models.CharField(max_length=255)),
                ('blue_link', models.CharField(max_length=255)),
            ],
        ),
    ]
