# Generated by Django 3.2.9 on 2021-11-30 14:07

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211126_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerrequest',
            name='resume',
            field=models.FileField(default=None, upload_to=home.models.upload_location),
        ),
    ]
