# Generated by Django 3.2.9 on 2021-11-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_careerrequest_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, choices=[('Customer Enquiry', 'Customer Enquiry'), ('Vendor Enquiry', 'Vendor Enquiry'), ('Press Coverage', 'Press Coverage'), ('Investors', 'Investors'), ('Others', 'Others')], max_length=255),
        ),
    ]
