# Generated by Django 3.2.9 on 2021-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Customer Enquiry', 'Customer Enquiry'), ('Vendor Enquiry', 'Vendor Enquiry'), ('Press Coverage', 'Press Coverage'), ('Investors', 'Investors'), ('Others', 'Others')], default=None, max_length=255),
        ),
    ]
