# Generated by Django 3.2.8 on 2021-10-25 10:21

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bloglist', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('snippet', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('author', models.CharField(default=None, max_length=100)),
                ('author_designation', models.TextField(default=None, max_length=100)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('image_main', models.FileField(null=True, upload_to=blog.models.upload_here)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
        ),
    ]
